name: PR-Security-Check

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    check_secret:
        name: Check Secrets
        runs-on: ubuntu-latest
        if: (github.actor != 'dependabot[bot]')
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
          
          - name: GitLeaks
            uses: gitleaks/gitleaks-action@v2
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    sast:
        name: Run Semgrep
        runs-on: ubuntu-latest
        if: (github.actor != 'dependabot[bot]')
        container:
          image: semgrep/semgrep
        steps:
          - uses: actions/checkout@v3
          - run: semgrep ci
            env:
              SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    sca_iac:
      name: Run Trivy
      runs-on: ubuntu-latest
      if: (github.actor != 'dependabot[bot]')
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Run Trivy vulnerability scanner in FS mode
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            hide-progress: false
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true
            severity: 'MEDIUM,HIGH,CRITICAL'

        - name: Run Trivy vulnerability scanner in IaC mode
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'config'
            hide-progress: false
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true
            severity: 'MEDIUM,HIGH,CRITICAL'

